name: FacesRegistration

options:
  minimumXcodeVersion: "15.0"
  deploymentTarget:
    iOS: "16.0"

targets:
  FacesRegistration:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: FacesRegistration
    dependencies: []
    preBuildScripts:
      - name: "Bundle React Native code and images"
        script: |
          set -e
          export NODE_BINARY=$(command -v node)
          REACT_NATIVE_PATH="${PODS_ROOT}/../../node_modules/react-native"
          WITH_ENVIRONMENT="${REACT_NATIVE_PATH}/scripts/xcode/with-environment.sh"
          REACT_NATIVE_XCODE="${REACT_NATIVE_PATH}/scripts/react-native-xcode.sh"
          /bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
        basedOnDependencyAnalysis: false
    settings:
      base:
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: FacesRegistration/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ai.unlikeother.facesregistration
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "59S95D279D"
        ENABLE_BITCODE: "NO"
        CLANG_ENABLE_MODULES: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
