require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'FacesDebug' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  pod 'AppReveal',
    :configurations => ['Debug'],
    :git => 'https://github.com/UnlikeOtherAI/AppReveal.git',
    :tag => '0.2.0'

  post_install do |installer|
    react_native_post_install(installer, :mac_catalyst_enabled => false)
  end
end
